### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [andreyPromaster/andreyPromaster.github.io#1]
Looks good in general! Thanks for the efforts, but need to make a few updates:
![image](https://user-images.githubusercontent.com/5592397/88588668-9b599a80-d060-11ea-8216-87a34d650339.png)

**Comment by andreyPromaster** [comment]
Thanks for your review) I have tried to fix this bugs.

**Comment by ilya4321** [comment]
Look good now, good attention to details
we will be checking your JS tasks soon, thanks for patience
